### PR TITLE
Refactor settings

### PR DESCRIPTION
**Pull request by sualko**
This is a follow up to #10

### CODE REVIEW

**Comment by sualko** [comment]
@leonvandebroek multiple `find*` functions for the `LicenseService` are returning nothing, see https://github.com/Sendent-B-V/Sendent-App-for-Nextcloud/blob/089fee8c53270ac50d2293557fd844e4c54b9f0c/lib/Service/LicenseService.php#L67

Is that intendet? Can you fix that on this branch?

**Comment by sualko** [comment]
I tried to make the settings js code a bit more readable, but I'm not sure if I broke something. Therefore a real good test is needed. In general I do not get the difference between group value (`/api/1.0/settinggroupvalue`) and key (`/api/1.0/settingkey`) endpoint. Why is this needed?

**Comment by leonvandebroek** [comment]
I've found that this setting is shown but it should not because advanced theming is disabled. 
image

**Comment by leonvandebroek** [comment]
The "Activate license" button doesn't work. I will send you a license key so you can test this via email.

**Comment by sualko** [comment]
Both issues has been resolved.

**Comment by sualko** [comment]
I just added a commit which determines the app version for the status api dynamically.

**Comment by leonvandebroek** [comment]
> I tried to make the settings js code a bit more readable, but I'm not sure if I broke something. Therefore a real good test is needed. In general I do not get the difference between group value (`/api/1.0/settinggroupvalue`) and key (`/api/1.0/settingkey`) endpoint. Why is this needed?

I first get the settingkeys and then get the settinggroupvalues and compare them in the add-in. For backward compatibility these endpoints cannot be removed. I just tested all the settings and they work as expected.

**Comment by leonvandebroek** [comment]
> @leonvandebroek multiple `find*` functions for the `LicenseService` are returning nothing, see
> 
> https://github.com/Sendent-B-V/Sendent-App-for-Nextcloud/blob/089fee8c53270ac50d2293557fd844e4c54b9f0c/lib/Service/LicenseService.php#L67
> 
> Is that intendet? Can you fix that on this branch?

Fixed with latest commit.

**Comment by leonvandebroek** [comment]
> I've found that this setting is shown but it should not because advanced theming is disabled.
> image

@sualko this was fixed when i ran yarn / yarn build commands.

**Comment by leonvandebroek** [comment]
@sualko i think we are ready to merge, do you agree?

**Pull request closed without merging**
