### PR TITLE
Add list setting input

### PR DESCRIPTION
**Pull request by sualko**
This is a follow up of #11 and allows to edit settings with multiple inputs more nicely. Entering multiple values separated by semicolon is not needed anymore. Since it is only adding some additional frontend code it's backwards compatible.

image

If you start typing something in the last input, a new input will appear.

### CODE REVIEW

**Comment by usselite** [comment]
Hi @sualko, Leon will handle the PR itself. UI related question from me, is this a seperate screen? As if it is at the same page as the rest of the settings that might be problematic for scenarios where the admin set for example 100 domain/email addresses in both fields. These lists can be very long.

**Comment by sualko** [comment]
It's on the same page, but I can add a toggle button to show/hide them.

**Comment by usselite** [comment]
That works also! :) If it is not to much work, perhaps combine it with limiting the length (div height) of the list, so it becomes scrollable?

**Comment by sualko** [comment]
I do not like scrollbars inside a page, but that's up to you. Currently it looks like this:

image

image

**Comment by leonvandebroek** [comment]
hi @sualko I just tested this PR and there is one settings which shows up where it shouldn't. Could you fix that?
image

**Comment by leonvandebroek** [comment]
> hi @sualko I just tested this PR and there is one settings which shows up where it shouldn't. Could you fix that?
> image

@sualko i tested this and it is fixed.

**Comment by leonvandebroek** [comment]
@sualko i think we are ready to merge this also, do you agree?

**Comment by sualko** [comment]
Lets go

**Pull request merged**
