### PR TITLE
add wysiwyg editor for snippets

### PR DESCRIPTION
**Pull request by sualko**
This is a first attempt to add [tinymce editor](https://www.tiny.cloud/docs/) for all HTML snippets.

Currently it looks like this:
image

Until this new feature can be merged we have to solve the following points:
- [x] handle images
- [x] test new flex layout
- [x] maybe load editor only on demand
- [x] add "is dirty" change on page unload

### CODE REVIEW

**Comment by usselite** [comment]
Hi @sualko, 

In the add-in I implemented a new tag {LOGO}, this replaces the old behavior of the 'CID' tags. 

The {LOGO} tags is derived from:
index.php/apps/theming/image/logo
or
index.php/apps/theming/image/logoheader

The latter is, I found on a very few occassions the logo is not set, but logoheader is. 

Could you  implement this? My tests look further OK.

**Comment by sualko** [comment]
@usselite can you elaborate a bit more on your request? I do not get it. Should I fix the handling of logo vs. logoheader, or should I add a {LOGO} tag, or should I render a image if there is a {LOGO} tag?

**Comment by usselite** [comment]
@sualko you should implement the latter. Implement the {LOGO} tag, that should render the image based upon either logo/logo header. I don't think you need to fix the issue with the Theming app.

**Comment by sualko** [comment]
It's still not clear to me. Should I add a button which inserts {LOGO}, or should I render some image if there is a {LOGO} tag?

**Comment by usselite** [comment]
@sualko sorry! Render the image tag {LOGO} if present within a IMG tag and add a button that inserts a IMG element that contains the logo element e.g.: ` (width height is sample)`. {LOGO} should redirect for the renderer then to the earlier mentioned links.

**Comment by sualko** [comment]
I think we are getting closer.

1. I add a button which inserts ``
2. If `{LOGO}` is inside a src attribute of an img tag, it should be replaced by a url (either `index.php/apps/theming/image/logo` or `index.php/apps/theming/image/logoheader`)

Is that right? Now it's only unclear which url I should use. Logo oder logoheader?

**Comment by sualko** [comment]
From my side this pr is ready to test. I only changed the behavior of the default logo url. Since there is no nice way to get the logoheader url and I also need a fallback, I just use the url of the logo in the header. It seams to me that the `index.php/apps/theming/image/logo` is used by default here (if there is a logo configured), but it works good so far.

**Pull request merged**
