### PR TITLE
Make strings translatable

### PR DESCRIPTION
**Pull request by sualko**
and prepare everything for Transifex.

### CODE REVIEW

**Comment by sualko** [comment]
@leonvandebroek please give @nextcloud-bot write access to this repository. See https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#setup-of-the-transifex-sync

**Comment by leonvandebroek** [comment]
@sualko i didn't update the master branch correctly, i just merged my changes from the development branch to the master branch and resolved all conflicts in the feat-translation branche as a result. Shall i complete the this PR?

**Comment by sualko** [comment]
I fixed a small issue, otherwise I think it's ready to be merged.

**Comment by leonvandebroek** [comment]
@sualko is it possible to test this somehow?

**Comment by sualko** [comment]
If you have time you can run all scripts which the Nextcloud translation bot is using and check if everything is going its way, but for me that would be an overkill.

**Pull request merged**
